### ISSUE TITLE
`prefixSkip` option injects 'is' by default

### ISSUE THREAD

**Issue by localusercamp** [cipami/nuxt-lodash#35]
Hi.

I think module should not provide array defaults, because it leads to cases where you cannot disable it completely.
For now for example i cannot alias check-functions (`isFinite`, `isBuffer` e.t.c) as `_isFinite` even if i set `prefixSkip: []`.

**Comment by localusercamp** [comment]
Because of reasons of backwards compatibility `prefixSkip` option may receive `false` as acceptable value for completely disabling that option. But in general i think it is incorrect approach to set defaults in array type options.

What do you think?

**Comment by cipami** [comment]
I agree, for now I fixed logic so that u can now disable with [] or false. To not introduce braking change 'is' is still default when not filled.

**Comment by localusercamp** [comment]
Thanks, thats great!
