### ISSUE TITLE
EError 

### ISSUE THREAD

**Issue by thibault60000** [cipami/nuxt-lodash#40]
Hi,

I have this issue with Nuxt3 
`"nuxt-lodash": "^2.4.1",`
`"nuxt": "3.0.0",`

When page loaded

<img width="542" alt="Capture d’écran 2023-01-27 à 18 36 57" src="https://user-images.githubusercontent.com/18366294/215155852-0550e6a5-336d-4ea8-b446-1b331eb26c73.png">

```
lodash: {
		prefix: "_",
		prefixSkip: ["string"],
		upperAfterPrefix: false,
		exclude: ["map"],
		alias: [
		  ["camelCase", "stringToCamelCase"], // => stringToCamelCase
		  ["kebabCase", "stringToKebab"], // => stringToKebab
		  ["isDate", "isLodashDate"], // => _isLodashDate
		],
	  },
	modules: [
		'@nuxtjs/apollo',
		'@nuxtjs/tailwindcss',
		'nuxt-lodash',
		'@nuxtjs/i18n',
		[ ....
```

Thanks :)

**Comment by cipami** [comment]
Seems line nuxt issue not this module, if you have further finding let me know.
