### ISSUE TITLE
Typo in module.ts

### ISSUE THREAD

**Issue by ConnorGDevelopment** [cipami/nuxt-lodash#45]
New to contributing, I think this is the correct way to suggest a change but apologies if not.

In "src/module.ts" there are a few typos, it doesn't affect functionality but could cause a future hiccup.

Current (Line 3):

`
import exculdeDefaults from './exclude'
`

Suggested (Line 3):

`
import excludeDefaults from './exclude'
`

Current (Line 61):
`
    const exludes = [...options.exclude, ...exculdeDefaults]
`

Suggested (Line 61):
`
    const excludes = [...options.exclude, ...excludeDefaults]
`

Current (Line 65):
`
      if (!exludes.includes(name)) {
`

Suggested (Line 65):
`
      if (!excludes.includes(name)) {
`

**Comment by cipami** [comment]
Fixed, thanks! Best way to contribute is to directly open Pull request with proposed changes.
