### ISSUE TITLE
question about optimizeDeps.exclude

### ISSUE THREAD

**Issue by krissss** [cipami/nuxt-lodash#47]
I want to know why exclude optimizeDeps `lodash-es` in `vite:extend`

This cause  so many dynamic import in dev, like this:

![image](https://github.com/cipami/nuxt-lodash/assets/10680903/f373b44d-23c8-4873-ba9a-260618fee97b)

Just a question, thank you.

**Comment by cipami** [comment]
Yea no longer needed it was some issue in RC. Thanks!
