### ISSUE TITLE
Fail with Nuxt 3.12

### ISSUE THREAD

**Issue by suchorski** [cipami/nuxt-lodash#63]
Failed to resolve dependency: aos, present in 'optimizeDeps.include'

Uncaught SyntaxError: The requested module 'http://localhost:6060/_nuxt/node_modules/.pnpm/lodash.throttle@4.1.1/node_modules/lodash.throttle/index.js?v=cf0afada' doesn't provide an export named: 'default'

**Comment by moloti** [comment]
Also have this issue

**Comment by suchorski** [comment]
Creating a plugin and injecting in nuxt works eell
