### ISSUE TITLE
Nuxt renamed useMeta to useHead and somehow this clashes

### ISSUE THREAD

**Issue by vanling** [cipami/nuxt-lodash#9]
Nuxt renamed useMeta to useHead and somehow this clashes. 

```
const useMeta: typeof import('../../node_modules/nuxt3/dist/head/runtime')['useMeta'] // deprecated
...
const useHead: typeof import('lodash-es')['head']
```

### Temp fix
For now i added `exclude: ['head'],` 
which results in 
```
  const useHead: typeof import('../../node_modules/nuxt3/dist/head/runtime')['useHead']
  const useMeta: typeof import('../../node_modules/nuxt3/dist/head/runtime')['useMeta']
  ```
  
Added a comment in the [breaking changes section](https://github.com/nuxt/framework/discussions/2883)

**Comment by cipami** [comment]
added `head` to exclude list by default as it is same as `first`. U can also alias `first` back to `head` when using different prefix.
